### ISSUE TITLE
MacOS Binary

### ISSUE THREAD

**Issue by rbheromax** [GameTheory-/mktool#1]
Is there any chance of getting a MacOS native binary?

**Comment by GameTheory-** [comment]
Sorry rbheromax, I don't have any experience with Mac OS, so it would be highly unlikely.

**Comment by t3zz** [comment]
Can I assisted on doing a port? I'm currently on macOS and it would greatly help my workflow testing kernel compiles for various Moto devices

**Comment by rbheromax** [comment]
Can I assisted on doing a port? I'm currently on macOS and it would greatly help my workflow testing kernel compiles for various Moto devices

**Comment by GameTheory-** [comment]
I just re-wrote mktool in java to give it a proper GUI. This also makes it easier to make it cross-platform. The source code is open so you can take a look and see where you can assist if possible.
